import { eqPinchQValue, eqPointerValue, rotaryDragValue } from "./control-physics.js";
import { adjacentRackTarget } from "./rack-navigation.js";
import { pluginPresentation } from "./plugin-presentation.js";
import { containedImagePoint } from "./native-pointer.js";

const $ = (selector) => document.querySelector(selector);
const els = { mixer:$("#mixer"), project:$("#project"), connection:$("#connection"), bank:$("#bankLabel"), settings:$("#settings"), host:$("#host"), port:$("#port"), pluginView:$("#pluginView"), panel:$("#parameterPanel"), tabs:$("#parameterTabs"), rack:$("#rackChain"), rackPosition:$("#rackPosition"), rackCount:$("#rackCount"), rackPrev:$("#rackPrev"), rackNext:$("#rackNext"), pluginLatency:$("#pluginLatency"), surface:$("#pluginSurface"), visual:$("#pluginVisual"), feedback:$("#touchFeedback"), fxBrowser:$("#fxBrowser"), fxSearch:$("#fxSearch"), fxResults:$("#fxResults") };
const settings = JSON.parse(localStorage.getItem("rtr.connection") || "null") || { host:location.hostname, port:location.port || "47830", auto:true };
// The origin that successfully served the app is the best authority after DHCP/network changes.
// Without this, a remembered WebSocket host can keep targeting yesterday's IP while the UI
// itself loads from today's IP, leaving a plausible-looking but disconnected mixer.
if (location.hostname && settings.host !== location.hostname) {
  settings.host = location.hostname;
  settings.port = location.port || "47830";
  localStorage.setItem("rtr.connection", JSON.stringify(settings));
}
let socket, heartbeat, reconnectTimer, state, bank=0, bankSize=8, latency=0, activeFX=null, activeParameterGroup=null, fxBrowserTrack=null, renameTarget=null, installedFX=null;
let nativeMode=false,nativeFXKey="",nativeSession=0,nativePointerId=null,nativeLastPoint=null,nativeMoveFrame=0,pendingNativeMove=null;
const pointers = new Map();
const interactionLocks = new Map();
const smoothCommands=new Map();let smoothFrame=0;
const EQ_GEOMETRY={width:1000,height:600,insetX:38,insetY:58};
let snapshots=JSON.parse(localStorage.getItem("rtr.snapshots")||"[]");
let userKeys=JSON.parse(localStorage.getItem("rtr.userKeys")||"[null,null,null,null]");

function connect() {
  clearTimeout(reconnectTimer); clearInterval(heartbeat);
  setConnection("connecting", "Connecting");
  socket?.close();
  socket = new WebSocket(`ws://${settings.host}:${settings.port}/ws`);
  socket.onopen = () => { setConnection("online", "REAPER"); socket.send(JSON.stringify({type:"hello",protocol:1})); heartbeat=setInterval(()=>socket.send(JSON.stringify({type:"heartbeat",at:Date.now()})),2000); };
  socket.onmessage = ({data}) => handle(JSON.parse(data));
  socket.onclose = () => { setConnection("offline", "Disconnected"); clearInterval(heartbeat); if(settings.auto) reconnectTimer=setTimeout(connect,1500); };
  socket.onerror = () => socket.close();
}
function handle(message) {
  if(message.type==="snapshot") { state=message.state; if(activeFX)renderPluginParameters();else render(); }
  if(message.type==="state_update" && state) { const changes=message.changes||{};for(const item of changes.meters||[]){const track=state.tracks.find(t=>t.id===item.id);if(track){track.meter=item.meter;track.signal=item.signal}}for(const item of changes.tracks||[]){const track=state.tracks.find(t=>t.id===item.id);if(!track)continue;for(const key of ["volume","pan","mute","solo","selected"])if(key in item)track[key]=item[key];for(const changedFX of item.fx||[]){const fx=track.fx.find(candidate=>changedFX.id?candidate.id===changedFX.id:candidate.index===changedFX.index);if(fx)fx.enabled=changedFX.enabled}}if(changes.selectedFx&&state.selectedFx&&changes.selectedFx.id===state.selectedFx.id){for(const changedParam of changes.selectedFx.parameters||[]){const param=state.selectedFx.parameters.find(candidate=>candidate.index===changedParam.index);if(param)Object.assign(param,changedParam)}}renderMeters();renderPluginSignal();if(changes.tracks?.length&&!activeFX)render();if(activeFX&&(changes.selectedFx?.parameters?.length||changes.tracks?.some(track=>track.fx?.length)))renderPluginParameters(); }
  if(message.type==="heartbeat") { latency=Math.max(0,Math.round((Date.now()-message.echo)/2));setConnection("online",`REAPER · ${latency} ms`); }
}
function command(action,target,value="") { if(socket?.readyState!==WebSocket.OPEN)return;const id=globalThis.crypto?.randomUUID?.()||`cmd-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;socket.send(JSON.stringify({type:"command",id,action,target,value})); }
function smoothCommand(action,target,value){smoothCommands.set(`${action}|${target}`,{action,target,value});if(smoothFrame)return;smoothFrame=requestAnimationFrame(()=>{smoothFrame=0;for(const item of smoothCommands.values())command(item.action,item.target,item.value);smoothCommands.clear()})}
function locallyControlled(key){const until=interactionLocks.get(key)||0;if(until>performance.now())return true;if(until)interactionLocks.delete(key);return pointers.has(key)}
function settleInteraction(key){interactionLocks.set(key,performance.now()+110);setTimeout(()=>{interactionLocks.delete(key);if(activeFX)renderPluginParameters()},120)}
function pressFeedback(element){if(!element)return;navigator.vibrate?.(6);element.classList.remove("tap-feedback");requestAnimationFrame(()=>element.classList.add("tap-feedback"));setTimeout(()=>element.classList.remove("tap-feedback"),360)}
let feedbackTimer;function announceFeedback(text){if(!els.feedback)return;clearTimeout(feedbackTimer);els.feedback.textContent=text;els.feedback.classList.add("show");feedbackTimer=setTimeout(()=>els.feedback.classList.remove("show"),850)}
function animateSurface(){els.surface.classList.remove("switching");requestAnimationFrame(()=>els.surface.classList.add("switching"));setTimeout(()=>els.surface.classList.remove("switching"),260)}
function render(){
  els.project.textContent=state.project.name||"Untitled"; bankSize=innerWidth<1180?8:12; document.documentElement.style.setProperty("--bank-size",bankSize); const count=Math.max(1,Math.ceil(state.tracks.length/bankSize));bank=Math.min(bank,count-1);els.bank.textContent=`${bank+1} / ${count}`;
  els.mixer.replaceChildren(...state.tracks.slice(bank*bankSize,(bank+1)*bankSize).map(trackStrip)); renderMeters();updateLiveKeys();
}
function trackStrip(track){
  const strip=document.createElement("article");strip.className=`strip ${track.selected?"selected":""}`;strip.dataset.id=track.id;
  strip.innerHTML=`<div class="track-head"><button class="track-select"><b>RACK ${track.number}</b><span></span><i class="rack-meter"><em class="meter-fill"></em></i></button><button class="rename-track" aria-label="Rename rack">✎</button></div><div class="fx-list"></div><div class="buttons"><button class="mute">MUTE</button><button class="solo">SOLO</button></div>`;
  strip.querySelector(".track-head span").textContent=track.name||`Track ${track.number}`;strip.querySelector(".track-select").onpointerup=()=>command("select_track",track.id);strip.querySelector(".rename-track").onclick=()=>openRenameRack(track);
  bindButton(strip.querySelector(".mute"),()=>command("set_track_mute",track.id,track.mute?0:1),track.mute);bindButton(strip.querySelector(".solo"),()=>command("set_track_solo",track.id,track.solo?0:1),track.solo);
  const list=strip.querySelector(".fx-list");track.fx.forEach((fx,visibleIndex)=>{const row=document.createElement("div");row.className="fx";row.setAttribute("role","button");row.innerHTML=`<small>${visibleIndex+1}</small><span></span><button class="bypass ${fx.enabled?"":"off"}" aria-label="Toggle bypass">${fx.enabled?"IN":"OUT"}</button>`;row.querySelector("span").textContent=fx.name;row.onpointerdown=e=>{if(e.target.classList.contains("bypass"))return;e.preventDefault();row.setPointerCapture(e.pointerId);row.classList.add("pressed")};row.onpointerup=e=>{row.classList.remove("pressed");if(e.target.classList.contains("bypass"))return;pressFeedback(row);openPlugin(track,fx)};row.onpointercancel=row.onlostpointercapture=()=>row.classList.remove("pressed");bindButton(row.querySelector(".bypass"),()=>command("set_fx_bypass",`${track.id}|${fx.index}`,fx.enabled?1:0));list.append(row)});for(let slot=track.fx.length;slot<Math.max(8,track.fx.length);slot++){const empty=document.createElement("button");empty.className="fx-empty";empty.innerHTML=`<small>${slot+1}</small><span>ADD PLUGIN</span>`;empty.onclick=()=>{pressFeedback(empty);openFxBrowser(track)};list.append(empty)}
  return strip;
}
async function openFxBrowser(track){
  fxBrowserTrack=track;$("#fxBrowserTrack").textContent=`${track.name||`Rack ${track.number}`} · add to the end of this chain`;els.fxSearch.value="";els.fxResults.replaceChildren();$("#fxBrowserStatus").textContent="Loading installed REAPER plug-ins…";els.fxBrowser.showModal();els.fxSearch.focus();
  if(!installedFX){try{const response=await fetch("/api/fx",{cache:"no-store"});if(!response.ok)throw new Error("inventory");installedFX=await response.json()}catch{$("#fxBrowserStatus").textContent="Restart the updated REAPER Bridge once to build the plug-in list.";return}}
  renderFxResults();
}
function renderFxResults(){
  if(!installedFX)return;const terms=els.fxSearch.value.trim().toLowerCase().split(/\s+/).filter(Boolean);const matches=installedFX.filter(fx=>terms.every(term=>`${fx.name} ${fx.ident}`.toLowerCase().includes(term))).slice(0,120);$("#fxBrowserStatus").textContent=`${matches.length}${matches.length===120?"+":""} shown · ${installedFX.length} installed`;
  els.fxResults.replaceChildren(...matches.map(fx=>{const button=document.createElement("button");button.className="fx-result";const type=(fx.name.match(/^([^:]+):/)?.[1]||"FX").toUpperCase();button.innerHTML='<b></b><span></span><small></small>';button.querySelector("b").textContent=type;button.querySelector("span").textContent=fx.name.replace(/^[^:]+:\s*/,"");button.querySelector("small").textContent=fx.ident||fx.name;button.onclick=()=>{if(!fxBrowserTrack)return;command("add_fx",fxBrowserTrack.id,fx.name);els.fxBrowser.close();flashButton($("#showPanel"),"ADDING FX")};return button}))
}
function openRenameRack(track){renameTarget=track;$("#rackName").value=track.name||`Track ${track.number}`;$("#renameRack").showModal();$("#rackName").focus();$("#rackName").select()}
function bindButton(button,callback,active=false){button.classList.toggle("active",active);button.onpointerdown=e=>{if(button.disabled)return;e.preventDefault();button.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{kind:"button",button});button.classList.add("pressed")};button.onpointerup=e=>{if(pointers.get(e.pointerId)?.button===button){button.classList.add("pending");pressFeedback(button);callback(button);setTimeout(()=>button.isConnected&&button.classList.remove("pending"),520)}pointers.delete(e.pointerId);button.classList.remove("pressed")};button.onpointercancel=button.onlostpointercapture=e=>{pointers.delete(e.pointerId);button.classList.remove("pressed")}}
function renderMeters(){if(!state)return;document.querySelectorAll(".strip").forEach(strip=>{const track=state.tracks.find(t=>t.id===strip.dataset.id);if(track){const peak=Math.max(...(track.meter||[-100]));strip.querySelector(".meter-fill").style.width=`${Math.max(0,Math.min(100,(peak+60)/60*100))}%`}})}
function fxIdentity(fx){return fx?`${fx.trackId}|${fx.id||fx.fxIndex}`:""}
function openPlugin(track,fx){const wasOpen=!els.pluginView.hidden;if(nativeMode)leaveNativeMode({rerender:false,stopCapture:false});activeFX={trackId:track.id,fxIndex:fx.index,id:fx.id,name:fx.name,enabled:fx.enabled};activeParameterGroup=null;command("open_fx",`${track.id}|${fx.index}`);$("#pluginTrack").textContent=track.name||`Rack ${track.number}`;$("#pluginName").textContent=fx.name;updateRackNavigation(track);renderRackChain(track);els.panel.dataset.key="";els.visual.dataset.key="";els.tabs.replaceChildren();els.panel.innerHTML='<div class="plugin-message">Loading real parameters from REAPER…</div>';els.visual.innerHTML='<div class="visual-loading">BUILDING TOUCH UI</div>';els.pluginView.hidden=false;if(wasOpen)animateSurface();else{els.pluginView.classList.add("revealing");setTimeout(()=>els.pluginView.classList.remove("revealing"),300)}renderPluginParameters()}
function closePlugin(){if(nativeMode)leaveNativeMode({rerender:false});command("close_fx",activeFX?`${activeFX.trackId}|${activeFX.fxIndex}`:"");activeFX=null;activeParameterGroup=null;els.panel.dataset.key="";els.visual.dataset.key="";els.tabs.replaceChildren();els.pluginView.hidden=true;render()}
function adjacentPlugin(delta){if(!activeFX||!state)return;const track=state.tracks.find(item=>item.id===activeFX.trackId);if(!track)return;const position=track.fx.findIndex(fx=>activeFX.id?fx.id===activeFX.id:fx.index===activeFX.fxIndex);const next=track.fx[position+delta];if(next)openPlugin(track,next)}
function adjacentRack(delta){if(!activeFX||!state)return;const current=state.tracks.find(track=>track.id===activeFX.trackId);if(!current)return;const slot=Math.max(0,current.fx.findIndex(fx=>activeFX.id?fx.id===activeFX.id:fx.index===activeFX.fxIndex));const target=adjacentRackTarget(state.tracks,activeFX.trackId,delta,slot);if(!target)return;announceFeedback(`RACK ${target.track.number} · ${target.track.name||`Track ${target.track.number}`}`);openPlugin(target.track,target.fx)}
function updateRackNavigation(track){if(!state||!track)return;const position=state.tracks.findIndex(item=>item.id===track.id);els.rackPosition.textContent=`RACK ${track.number} · ${position+1} / ${state.tracks.length}`;els.rackCount.textContent=`${track.fx.length} FX`;const available=Boolean(adjacentRackTarget(state.tracks,track.id,1));els.rackPrev.disabled=!available;els.rackNext.disabled=!available}
function renderRackChain(track){updateRackNavigation(track);const key=`${track.id}|${activeFX?.id||activeFX?.fxIndex}|${track.fx.map(fx=>`${fx.id}:${fx.enabled?1:0}`).join(";")}`;if(els.rack.dataset.key===key)return;els.rack.dataset.key=key;els.rack.replaceChildren(...track.fx.map((fx,visibleIndex)=>{const button=document.createElement("button");const active=activeFX&&(activeFX.id?fx.id===activeFX.id:fx.index===activeFX.fxIndex);button.className=`rack-slot ${active?"active":""}`;button.innerHTML=`<small>SLOT ${visibleIndex+1}</small><span></span><i>${fx.enabled?"ON":"OFF"}</i>`;button.querySelector("span").textContent=fx.name;bindButton(button,()=>openPlugin(track,fx));return button}))}
function renderPluginParameters(){
  const selected=state?.selectedFx;if(!activeFX||!selected||selected.trackId!==activeFX.trackId)return;if(selected.id&&activeFX.id===selected.id)activeFX.fxIndex=selected.fxIndex;else if(selected.fxIndex!==activeFX.fxIndex)return;activeFX.id=selected.id||activeFX.id;
  const params=usableParameters(selected.parameters,selected.name);
  const groups=new Map();for(const param of params){const descriptor=classifyParameter(param,selected.name);const renamed={...param,name:descriptor.name};if(!groups.has(descriptor.group))groups.set(descriptor.group,[]);groups.get(descriptor.group).push(renamed)}const groupNames=[...groups.keys()];if(!activeParameterGroup||!groups.has(activeParameterGroup))activeParameterGroup=/\bF6\b/i.test(selected.name)&&groups.has("BAND 1")?"BAND 1":groupNames.find(name=>name!=="I/O"&&name!=="GENERAL")||groupNames[0]||null;
  const key=`${selected.trackId}|${selected.fxIndex}|${activeParameterGroup}|${params.map(param=>`${param.index}:${param.name}:${param.toggle?1:0}:${param.step||0}`).join(";")}`;$("#pluginName").textContent=selected.name;
  const activeTrack=state.tracks.find(track=>track.id===activeFX.trackId);const liveFX=activeTrack?.fx.find(fx=>activeFX.id?fx.id===activeFX.id:fx.index===activeFX.fxIndex);if(liveFX){activeFX.fxIndex=liveFX.index;activeFX.enabled=liveFX.enabled;$("#pluginBypass").textContent=liveFX.enabled?"ACTIVE":"BYPASSED";$("#pluginBypass").classList.toggle("active",!liveFX.enabled)}if(activeTrack){$("#pluginTrack").textContent=activeTrack.name||`Track ${activeTrack.number}`;renderRackChain(activeTrack)}
  if(nativeMode&&nativeFXKey===fxIdentity(selected))return;
  renderPluginVisual(selected,params);
  if(els.panel.dataset.key===key){for(const param of params){const shell=els.panel.querySelector(`.parameter[data-index="${param.index}"]`);if(!shell||locallyControlled(`fx:${param.index}`))continue;shell.dataset.value=param.value;const input=shell.querySelector("input[type=range]");const select=shell.querySelector("select");const knob=shell.querySelector(".knob");const output=shell.querySelector("output");const toggle=shell.querySelector("button[data-role=toggle]");if(input)input.value=param.value;if(select){const options=[...select.options];const nearest=options.reduce((best,option)=>Math.abs(+option.value-param.value)<Math.abs(+best.value-param.value)?option:best,options[0]);if(nearest)select.value=nearest.value}if(knob)paintKnob(knob,param.value);if(output)output.textContent=param.formatted||`${Math.round(param.value*100)}%`;if(toggle){toggle.dataset.value=param.value;toggle.textContent=param.formatted||(+param.value>.5?"ON":"OFF");toggle.classList.toggle("on",+param.value>.5);toggle.classList.remove("pending")}}return}
  if(!params.length){els.tabs.replaceChildren();els.panel.dataset.key=key;els.panel.innerHTML='<div class="plugin-message native-required"><strong>這個插件沒有提供可自動化參數</strong><span>可切換到插件自己的原生畫面直接操作。</span><button>開啟原生介面</button></div>';bindButton(els.panel.querySelector("button"),()=>enterNativeMode(selected));return}
  els.tabs.replaceChildren(...groupNames.map(name=>{const button=document.createElement("button");button.textContent=name;button.classList.toggle("active",name===activeParameterGroup);bindButton(button,()=>{if(activeParameterGroup===name)return;activeParameterGroup=name;els.panel.dataset.key="";renderPluginParameters()});return button}));const section=document.createElement("section");section.className="parameter-section active-page";section.innerHTML='<h3></h3><div class="parameter-grid"></div>';section.querySelector("h3").textContent=activeParameterGroup;section.querySelector(".parameter-grid").replaceChildren(...(groups.get(activeParameterGroup)||[]).map(param=>parameterControl(param,selected)));els.panel.dataset.key=key;els.panel.replaceChildren(section)
}
function usableParameters(parameters=[]){
  const midiStart=parameters.findIndex(param=>/^Pitch Bend$/i.test(param.name));
  const hasHostMidiBlock=midiStart>=0&&parameters.slice(midiStart+1,midiStart+8).some(param=>/^(After Touch|Bank Select|Modulation Wheel|Breath Controller|Foot Controller|Control \d+)$/i.test(param.name));
  const core=hasHostMidiBlock?parameters.slice(0,midiStart):parameters;
  const utilities=parameters.filter(param=>/^(Bypass|Wet|Delta)$/i.test(param.name));
  return [...core,...utilities.filter(param=>!core.some(item=>item.index===param.index))].filter(param=>param.name&&!/^Control \d+$/i.test(param.name));
}
function eqBandParameter(params,band,kind){
  const patterns={freq:new RegExp(`^Band\\s*${band}\\s*(?:Freq|Frequency)$`,"i"),gain:new RegExp(`^Band\\s*${band}\\s*Gain$`,"i"),q:new RegExp(`^Band\\s*${band}\\s*Q$`,"i"),enabled:new RegExp(`^Band\\s*${band}\\s*(?:On/Off|Enable(?:d)?)$`,"i")};
  return params.find(param=>patterns[kind].test(param.name||""));
}
function directEQBands(params){const candidates=new Set();for(const param of params){const match=(param.name||"").match(/^Band\s*(\d+)\s*(?:Freq|Frequency)$/i);if(match)candidates.add(+match[1])}return [...candidates].filter(band=>eqBandParameter(params,band,"gain")).sort((a,b)=>a-b)}
function renderPluginVisual(selected,params){
  const eqBands=directEQBands(params);const isDirectEQ=eqBands.length>=2;const presentation=pluginPresentation(selected.name,params);els.surface.classList.toggle("direct-eq",isDirectEQ);if(!isDirectEQ)els.surface.classList.remove("eq-details-open");els.pluginView.dataset.pluginKind=isDirectEQ?"equalizer":presentation.kind;els.pluginView.style.setProperty("--plugin-accent",isDirectEQ?"#d99058":presentation.accent);
  const visualKey=`${selected.trackId}|${selected.fxIndex}|${isDirectEQ?`direct-eq-${eqBands.join("-")}`:presentation.kind}`;
  if(els.visual.dataset.key!==visualKey){els.visual.dataset.key=visualKey;isDirectEQ?buildDirectEQVisual(selected,params,eqBands):buildGenericVisual(selected,params,presentation)}
  if(isDirectEQ)updateDirectEQVisual(params,eqBands);renderPluginSignal();
}
function buildDirectEQVisual(selected,initialParams,bands){
  els.visual.innerHTML='<div class="visual-head eq-toolbar"><div><strong>DIRECT TOUCH EQ</strong><span>單指拖曳頻率／增益 · 第二指捏合調整 Q</span></div><div class="visual-head-actions"><div class="live-levels"><span>IN<i><b data-level="input"></b></i></span><span>OUT<i><b data-level="output"></b></i></span></div><button class="eq-details-toggle">細節參數</button><button class="native-entry">原生介面</button></div></div><div class="eq-canvas"><svg class="eq-graph" viewBox="0 0 1000 600" preserveAspectRatio="none" aria-label="Direct touch EQ graph"><defs><linearGradient id="rtaInput" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#36d8ff" stop-opacity=".5"/><stop offset="1" stop-color="#36d8ff" stop-opacity=".02"/></linearGradient><linearGradient id="rtaOutput" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#77efb0"/><stop offset=".78" stop-color="#f0c65a"/><stop offset="1" stop-color="#ff6375"/></linearGradient></defs><g class="eq-grid"></g><path class="rt-spectrum rt-spectrum-input"></path><path class="rt-spectrum-output"></path><line class="eq-zero" x1="0" x2="1000" y1="300" y2="300"></line><path class="eq-curve-shadow"></path><path class="eq-curve"></path><g class="eq-bands"></g></svg><div class="eq-gesture-status">拖動節點 · 兩指捏合 Q</div><div class="eq-rta-legend"><span><i></i>INPUT RTA</span><span><i></i>OUTPUT RTA</span></div></div>';
  bindButton(els.visual.querySelector(".native-entry"),()=>enterNativeMode(selected));const details=els.visual.querySelector(".eq-details-toggle");bindButton(details,()=>{const open=els.surface.classList.toggle("eq-details-open");details.textContent=open?"關閉細節":"細節參數"});
  const svgNS="http://www.w3.org/2000/svg";const grid=els.visual.querySelector(".eq-grid");const frequencies=[20,50,100,200,500,1000,2000,5000,10000,20000];for(const frequency of frequencies){const normalized=Math.log10(frequency/20)/3;const x=EQ_GEOMETRY.insetX+normalized*(EQ_GEOMETRY.width-EQ_GEOMETRY.insetX*2);const line=document.createElementNS(svgNS,"line");line.setAttribute("x1",x);line.setAttribute("x2",x);line.setAttribute("y1",EQ_GEOMETRY.insetY);line.setAttribute("y2",EQ_GEOMETRY.height-EQ_GEOMETRY.insetY);const label=document.createElementNS(svgNS,"text");label.setAttribute("x",x);label.setAttribute("y",EQ_GEOMETRY.height-18);label.setAttribute("text-anchor","middle");label.textContent=frequency>=1000?`${frequency/1000}k`:frequency;grid.append(line,label)}for(let index=0;index<=6;index++){const y=EQ_GEOMETRY.insetY+index/6*(EQ_GEOMETRY.height-EQ_GEOMETRY.insetY*2);const line=document.createElementNS(svgNS,"line");line.setAttribute("x1",EQ_GEOMETRY.insetX);line.setAttribute("x2",EQ_GEOMETRY.width-EQ_GEOMETRY.insetX);line.setAttribute("y1",y);line.setAttribute("y2",y);const label=document.createElementNS(svgNS,"text");label.setAttribute("x",9);label.setAttribute("y",y+4);label.textContent=`${18-index*6>0?"+":""}${18-index*6}`;grid.append(line,label)}
  const bandLayer=els.visual.querySelector(".eq-bands");for(const band of bands){const group=document.createElementNS(svgNS,"g");group.dataset.band=band;group.dataset.enabled="1";const width=document.createElementNS(svgNS,"ellipse");width.setAttribute("class","band-q-width");width.setAttribute("rx",80);width.setAttribute("ry",22);const hit=document.createElementNS(svgNS,"circle");hit.setAttribute("r",50);hit.setAttribute("class","band-hit");const halo=document.createElementNS(svgNS,"circle");halo.setAttribute("r",30);halo.setAttribute("class","band-halo");const node=document.createElementNS(svgNS,"circle");node.setAttribute("r",17);node.setAttribute("class","band-node");const number=document.createElementNS(svgNS,"text");number.setAttribute("y",5);number.setAttribute("text-anchor","middle");number.textContent=band;const readout=document.createElementNS(svgNS,"g");readout.setAttribute("class","band-readout");const back=document.createElementNS(svgNS,"rect");back.setAttribute("x",-83);back.setAttribute("y",-23);back.setAttribute("width",166);back.setAttribute("height",44);back.setAttribute("rx",9);const value=document.createElementNS(svgNS,"text");value.setAttribute("class","band-value");value.setAttribute("y",-5);value.setAttribute("text-anchor","middle");const q=document.createElementNS(svgNS,"text");q.setAttribute("class","band-q-value");q.setAttribute("y",13);q.setAttribute("text-anchor","middle");readout.append(back,value,q);group.append(width,hit,halo,node,number,readout);bandLayer.append(group)}
  const graph=els.visual.querySelector(".eq-graph"),touches=new Map(),pinches=new Map();const currentParams=()=>state?.selectedFx?.id===selected.id?state.selectedFx.parameters:initialParams;const touchesFor=band=>[...touches.entries()].filter(([,touch])=>touch.band===band);const graphPoint=event=>eqPointerValue(event.clientX,event.clientY,graph.getBoundingClientRect(),EQ_GEOMETRY);
  const selectBand=event=>{const direct=event.target.closest?.("[data-band]");if(direct)return +direct.dataset.band;const point=graphPoint(event);let nearest=null,best=Infinity;for(const band of bands){const group=graph.querySelector(`[data-band="${band}"]`);const distance=Math.hypot(point.x-(+group.dataset.x||0),point.y-(+group.dataset.y||0));if(distance<best){best=distance;nearest=band}}if(best<=95)return nearest;const active=[...new Set([...touches.values()].map(touch=>touch.band))];return active.length===1?active[0]:null};
  const showGesture=(band,freqText,gainText,qText)=>{const status=els.visual.querySelector(".eq-gesture-status");status.textContent=`BAND ${band}  ·  ${freqText}  ·  ${gainText}  ·  ${qText}`;status.classList.add("active")};
  const moveBand=(event,touch)=>{const raw=graphPoint(event),group=graph.querySelector(`[data-band="${touch.band}"]`);const x=Math.max(EQ_GEOMETRY.insetX,Math.min(EQ_GEOMETRY.width-EQ_GEOMETRY.insetX,raw.x-touch.offsetX)),y=Math.max(EQ_GEOMETRY.insetY,Math.min(EQ_GEOMETRY.height-EQ_GEOMETRY.insetY,raw.y-touch.offsetY));const frequency=(x-EQ_GEOMETRY.insetX)/(EQ_GEOMETRY.width-EQ_GEOMETRY.insetX*2),gain=1-(y-EQ_GEOMETRY.insetY)/(EQ_GEOMETRY.height-EQ_GEOMETRY.insetY*2);const params=currentParams(),freq=eqBandParameter(params,touch.band,"freq"),gainParam=eqBandParameter(params,touch.band,"gain"),q=eqBandParameter(params,touch.band,"q");if(!freq||!gainParam)return;group.dataset.x=x;group.dataset.y=y;group.setAttribute("transform",`translate(${x} ${y})`);const freqText=formatEQFrequency(frequency),gainText=formatEQGain(gain),qText=q?.formatted||formatEQQ(+group.dataset.q||.5);setBandReadout(group,freqText,gainText,qText);showGesture(touch.band,freqText,gainText,qText);smoothCommand("set_fx_param",`${selected.trackId}|${selected.fxIndex}|${freq.index}`,frequency);smoothCommand("set_fx_param",`${selected.trackId}|${selected.fxIndex}|${gainParam.index}`,gain);drawEQCurve(graph)};
  const updatePinch=band=>{const pair=touchesFor(band);if(pair.length<2){pinches.delete(band);return}const distance=Math.hypot(pair[0][1].clientX-pair[1][1].clientX,pair[0][1].clientY-pair[1][1].clientY);const params=currentParams(),q=eqBandParameter(params,band,"q");if(!q)return;let pinch=pinches.get(band);if(!pinch){pinch={distance,origin:+q.value||0};pinches.set(band,pinch);graph.querySelector(`[data-band="${band}"]`)?.classList.add("pinching");navigator.vibrate?.(7)}const value=eqPinchQValue(pinch.origin,pinch.distance,distance),group=graph.querySelector(`[data-band="${band}"]`);group.dataset.q=value;updateBandQWidth(group);setBandReadout(group,eqBandParameter(params,band,"freq")?.formatted||"—",eqBandParameter(params,band,"gain")?.formatted||"—",formatEQQ(value));showGesture(band,eqBandParameter(params,band,"freq")?.formatted||"—",eqBandParameter(params,band,"gain")?.formatted||"—",formatEQQ(value));smoothCommand("set_fx_param",`${selected.trackId}|${selected.fxIndex}|${q.index}`,value);drawEQCurve(graph)};
  graph.onpointerdown=event=>{const band=selectBand(event);if(!band||touchesFor(band).length>=2)return;event.preventDefault();const point=graphPoint(event),group=graph.querySelector(`[data-band="${band}"]`),existing=touchesFor(band);const touch={band,clientX:event.clientX,clientY:event.clientY,offsetX:existing.length?0:point.x-(+group.dataset.x||point.x),offsetY:existing.length?0:point.y-(+group.dataset.y||point.y)};touches.set(event.pointerId,touch);graph.setPointerCapture(event.pointerId);pointers.set(`graph:${band}`,true);group.classList.add("dragging");if(activeParameterGroup!==`BAND ${band}`){activeParameterGroup=`BAND ${band}`;els.panel.dataset.key="";renderPluginParameters()}if(existing.length)updatePinch(band);else navigator.vibrate?.(5)};
  graph.onpointermove=event=>{const touch=touches.get(event.pointerId);if(!touch)return;event.preventDefault();touch.clientX=event.clientX;touch.clientY=event.clientY;const bandTouches=touchesFor(touch.band);if(bandTouches[0]?.[0]===event.pointerId)moveBand(event,touch);if(bandTouches.length>=2)updatePinch(touch.band)};
  const end=event=>{const touch=touches.get(event.pointerId);if(!touch)return;event.preventDefault();const band=touch.band;touches.delete(event.pointerId);const remaining=touchesFor(band),group=graph.querySelector(`[data-band="${band}"]`);if(remaining.length<2){pinches.delete(band);group?.classList.remove("pinching")}if(!remaining.length){pointers.delete(`graph:${band}`);group?.classList.remove("dragging");settleInteraction(`graph:${band}`);setTimeout(()=>{if(!touches.size){const status=els.visual.querySelector(".eq-gesture-status");status?.classList.remove("active");if(status)status.textContent="拖動節點 · 兩指捏合 Q"}},360)}};graph.onpointerup=end;graph.onpointercancel=end;graph.onlostpointercapture=end;
}
function formatEQFrequency(value){const hz=20*Math.pow(1000,Math.max(0,Math.min(1,+value||0)));return hz>=1000?`${(hz/1000).toFixed(hz>=10000?1:2)} kHz`:`${Math.round(hz)} Hz`}
function formatEQGain(value){const gain=(Math.max(0,Math.min(1,+value||0))-.5)*36;return `${gain>=0?"+":""}${gain.toFixed(1)} dB`}
function formatEQQ(value){return `Q ${(0.4*Math.pow(250,Math.max(0,Math.min(1,+value||0)))).toFixed(2)}`}
function setBandReadout(group,frequency,gain,q){if(!group)return;group.querySelector(".band-value").textContent=`${frequency}  ·  ${gain}`;group.querySelector(".band-q-value").textContent=q.startsWith("Q")?q:`Q ${q}`;const x=+group.dataset.x||0,y=+group.dataset.y||0;const shiftX=x<140?72:x>860?-72:0;group.querySelector(".band-readout").setAttribute("transform",`translate(${shiftX} ${y<135?76:-76})`)}
function updateBandQWidth(group){if(!group)return;const q=Math.max(0,Math.min(1,+group.dataset.q||0));group.querySelector(".band-q-width")?.setAttribute("rx",24+(1-q)*150)}
function drawEQCurve(graph){if(!graph)return;const groups=[...graph.querySelectorAll(".eq-bands>[data-band]")].filter(group=>group.dataset.enabled!=="0");const middle=EQ_GEOMETRY.height/2,points=[];for(let x=0;x<=EQ_GEOMETRY.width;x+=6){let response=0;for(const group of groups){const center=+group.dataset.x||middle,y=+group.dataset.y||middle,q=Math.max(0,Math.min(1,+group.dataset.q||0)),width=24+(1-q)*150;response+=(middle-y)*Math.exp(-.5*Math.pow((x-center)/width,2))}points.push([x,Math.max(EQ_GEOMETRY.insetY,Math.min(EQ_GEOMETRY.height-EQ_GEOMETRY.insetY,middle-response))])}const d=`M ${points.map(point=>`${point[0]} ${point[1]}`).join(" L ")}`;graph.querySelector(".eq-curve")?.setAttribute("d",d);graph.querySelector(".eq-curve-shadow")?.setAttribute("d",d)}
function updateDirectEQVisual(params,bands){const graph=els.visual.querySelector(".eq-graph");if(!graph)return;for(const band of bands){const freq=eqBandParameter(params,band,"freq"),gain=eqBandParameter(params,band,"gain"),q=eqBandParameter(params,band,"q"),enabled=eqBandParameter(params,band,"enabled");if(!freq||!gain)continue;const x=EQ_GEOMETRY.insetX+(+freq.value*(EQ_GEOMETRY.width-EQ_GEOMETRY.insetX*2)),y=EQ_GEOMETRY.insetY+((1-(+gain.value))*(EQ_GEOMETRY.height-EQ_GEOMETRY.insetY*2)),group=graph.querySelector(`[data-band="${band}"]`);if(!group)continue;if(!locallyControlled(`graph:${band}`)){group.dataset.x=x;group.dataset.y=y;group.dataset.q=q?.value??.5;group.setAttribute("transform",`translate(${x} ${y})`)}group.dataset.enabled=enabled&&+enabled.value<.5?"0":"1";group.classList.toggle("off",group.dataset.enabled==="0");group.classList.toggle("selected",activeParameterGroup===`BAND ${band}`);updateBandQWidth(group);setBandReadout(group,freq.formatted||formatEQFrequency(freq.value),gain.formatted||formatEQGain(gain.value),q?.formatted||formatEQQ(q?.value??.5))}drawEQCurve(graph)}
function buildGenericVisual(selected,params,presentation){const groups=[...new Set(params.map(param=>classifyParameter(param,selected.name).group))].slice(0,6);els.visual.innerHTML='<div class="generic-visual"><div class="fx-glyph"></div><div class="generic-title"><strong></strong><span></span><div class="visual-tags"></div><div class="live-levels"><span>IN<i><b data-level="input"></b></i></span><span>OUT<i><b data-level="output"></b></i></span></div><button class="native-entry">原生介面</button></div><svg viewBox="0 0 500 100" preserveAspectRatio="none"><path class="rt-spectrum-line" d="M0 80 L500 80"></path></svg></div>';els.visual.querySelector(".fx-glyph").textContent=presentation.label;els.visual.querySelector(".generic-title strong").textContent=selected.name;els.visual.querySelector(".generic-title span").textContent=`${presentation.kind.toUpperCase()} · ${params.length} live controls`;const tags=els.visual.querySelector(".visual-tags");for(const group of groups){const tag=document.createElement("b");tag.textContent=group;tags.append(tag)}bindButton(els.visual.querySelector(".native-entry"),()=>enterNativeMode(selected))}

async function enterNativeMode(selected=state?.selectedFx){
  if(!selected||!activeFX)return;nativeMode=true;nativeFXKey=fxIdentity(selected);const session=++nativeSession;nativePointerId=null;nativeLastPoint=null;els.surface.classList.add("native-active");els.tabs.replaceChildren();els.panel.dataset.key="";els.visual.dataset.key=`native|${nativeFXKey}`;els.visual.innerHTML='<div class="native-surface"><img draggable="false" alt="插件原生介面"><div class="native-status loading"><i></i><span>等待指定插件視窗…</span></div><button class="native-exit">‹ 參數模式</button></div>';bindButton(els.visual.querySelector(".native-exit"),()=>leaveNativeMode());command("open_native_fx",`${selected.trackId}|${selected.fxIndex}`);announceFeedback("原生介面 · 等待插件視窗");
  const key=nativeFXKey;while(nativeMode&&nativeFXKey===key&&nativeSession===session){let wait=550;try{const response=await fetch("/capture/select",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:selected.name}),cache:"no-store"});if(response.ok){activateNativeStream(key);return}const detail=await response.json().catch(()=>({}));const status=els.visual.querySelector(".native-status span");if(status)status.textContent=(detail.error||"").includes("matched")?"等待你在 REAPER 開啟這個插件…":"等待原生畫面服務…";wait=(detail.error||"").includes("matched")?550:1400}catch{const status=els.visual.querySelector(".native-status span");if(status)status.textContent="等待原生畫面服務…";wait=1400}await new Promise(resolve=>setTimeout(resolve,wait))}
}
function activateNativeStream(key){if(!nativeMode||nativeFXKey!==key)return;const image=els.visual.querySelector(".native-surface img");const status=els.visual.querySelector(".native-status");if(!image||!status)return;image.src=`/capture/stream.mjpeg?${Date.now()}`;image.onload=()=>{if(!nativeMode||nativeFXKey!==key)return;status.classList.remove("loading","error");status.classList.add("online");status.querySelector("span").textContent="插件原生畫面 · 單指模式"};bindNativePointer(image)}
function leaveNativeMode({rerender=true,stopCapture=true}={}){if(!nativeMode)return;const target=activeFX?`${activeFX.trackId}|${activeFX.fxIndex}`:"";if(target)command("close_native_fx",target);if(stopCapture)fetch("/capture/stop",{method:"POST",cache:"no-store"}).catch(()=>{});nativeMode=false;nativeFXKey="";nativeSession++;nativePointerId=null;nativeLastPoint=null;pendingNativeMove=null;if(nativeMoveFrame)cancelAnimationFrame(nativeMoveFrame);nativeMoveFrame=0;els.surface.classList.remove("native-active");els.visual.dataset.key="";els.panel.dataset.key="";if(rerender)renderPluginParameters()}
function sendNativeInput(action,point){if(!point||!nativeMode)return;fetch("/capture/input",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...point}),cache:"no-store"}).catch(()=>{})}
function queueNativeMove(point){pendingNativeMove=point;if(nativeMoveFrame)return;nativeMoveFrame=requestAnimationFrame(()=>{nativeMoveFrame=0;const next=pendingNativeMove;pendingNativeMove=null;sendNativeInput("move",next)})}
function bindNativePointer(image){const pointFor=event=>containedImagePoint(event.clientX,event.clientY,image.getBoundingClientRect(),image.naturalWidth,image.naturalHeight);image.onpointerdown=event=>{if(nativePointerId!==null)return;const point=pointFor(event);if(!point)return;event.preventDefault();nativePointerId=event.pointerId;nativeLastPoint=point;image.setPointerCapture(event.pointerId);image.classList.add("touching");navigator.vibrate?.(5);sendNativeInput("down",point)};image.onpointermove=event=>{if(nativePointerId!==event.pointerId)return;const point=pointFor(event);if(!point)return;event.preventDefault();nativeLastPoint=point;queueNativeMove(point)};const end=event=>{if(nativePointerId!==event.pointerId)return;event.preventDefault();const point=pointFor(event)||nativeLastPoint;pendingNativeMove=null;if(nativeMoveFrame)cancelAnimationFrame(nativeMoveFrame);nativeMoveFrame=0;sendNativeInput("up",point);nativePointerId=null;nativeLastPoint=null;image.classList.remove("touching")};image.onpointerup=end;image.onpointercancel=end;image.onlostpointercapture=end}
function renderPluginSignal(){if(!activeFX||!state||!els.visual)return;const track=state.tracks.find(item=>item.id===activeFX.trackId);if(!track)return;const signal=track.signal,inputStage=signal?.input||signal,outputStage=signal?.output;const input=Math.max(+(inputStage?.left||0),+(inputStage?.right||0));const outputDb=Math.max(...(track.meter||[-100])),fallbackOutput=Math.max(0,Math.min(1,(outputDb+60)/60)),output=outputStage?Math.max(+(outputStage.left||0),+(outputStage.right||0)):fallbackOutput;const inputBar=els.visual.querySelector('[data-level="input"]'),outputBar=els.visual.querySelector('[data-level="output"]');if(inputBar)inputBar.style.width=`${Math.max(0,Math.min(100,input*100))}%`;if(outputBar)outputBar.style.width=`${Math.max(0,Math.min(100,output*100))}%`;const inputSpectrum=inputStage?.spectrum,outputSpectrum=outputStage?.spectrum;if(Array.isArray(inputSpectrum)&&inputSpectrum.length){const eqPath=els.visual.querySelector(".rt-spectrum-input");if(eqPath){const points=inputSpectrum.map((value,index)=>`${index/(inputSpectrum.length-1)*EQ_GEOMETRY.width} ${(1-Math.max(0,Math.min(1,+value||0)))*(EQ_GEOMETRY.height-EQ_GEOMETRY.insetY)+EQ_GEOMETRY.insetY/2}`);eqPath.setAttribute("d",`M 0 ${EQ_GEOMETRY.height} L ${points.join(" L ")} L ${EQ_GEOMETRY.width} ${EQ_GEOMETRY.height} Z`)}const genericPath=els.visual.querySelector(".rt-spectrum-line");if(genericPath){const points=inputSpectrum.map((value,index)=>`${index/(inputSpectrum.length-1)*500} ${(1-Math.max(0,Math.min(1,+value||0)))*90+5}`);genericPath.setAttribute("d",`M ${points.join(" L ")}`)}}if(Array.isArray(outputSpectrum)&&outputSpectrum.length){const outputPath=els.visual.querySelector(".rt-spectrum-output");if(outputPath){const points=outputSpectrum.map((value,index)=>`${index/(outputSpectrum.length-1)*EQ_GEOMETRY.width} ${(1-Math.max(0,Math.min(1,+value||0)))*(EQ_GEOMETRY.height-EQ_GEOMETRY.insetY)+EQ_GEOMETRY.insetY/2}`);outputPath.setAttribute("d",`M ${points.join(" L ")}`)}}}
function paintKnob(knob,value){const normalized=Math.max(0,Math.min(1,+value||0));knob.style.setProperty("--angle",`${-135+normalized*270}deg`);knob.style.setProperty("--fill",`${normalized*75}%`);knob.setAttribute("aria-valuenow",normalized)}
function classifyParameter(param,fxName=""){
  const name=(param.name||`Parameter ${param.index+1}`).trim();
  const indexed=name.match(/^(Band|Channel|Osc(?:illator)?|LFO|Envelope|Env|Filter|Layer|Part)\s*(\d+)\s*[-:]?\s*(.+)$/i);
  if(indexed)return{group:`${indexed[1].toUpperCase()} ${indexed[2]}`,name:indexed[3]};
  if(/\bF6\b/i.test(fxName)&&/^(HPF|LPF)/i.test(name))return{group:"GLOBAL / FILTERS",name};
  if(/threshold|ratio|attack|release|knee|range|compress|limiter|gate|expan|transient|hold/i.test(name))return{group:"DYNAMICS",name};
  if(/reverb|decay|damping|diffusion|room|size|early reflection|late reflection/i.test(name))return{group:"SPACE",name};
  if(/frequency|\bfreq\b|\bq\b|filter|cutoff|resonan|high.?pass|low.?pass|\bHPF\b|\bLPF\b|\bEQ\b|shelf|bell/i.test(name))return{group:"FILTER / EQ",name};
  if(/pitch|formant|transpose|detune|semitone|\bcents?\b/i.test(name))return{group:"PITCH",name};
  if(/stereo|mono|mid.?side|phase|correlation|image/i.test(name))return{group:"IMAGE",name};
  if(/\bLFO\b|modulat|chorus|flang|phaser|depth|waveform|shape/i.test(name))return{group:"MODULATION",name};
  if(/delay|\btime\b|tempo|sync|\brate\b|speed|feedback|pre.?delay|division/i.test(name))return{group:"TIME",name};
  if(/drive|satur|distort|tone|color|colour|warm|character|harmonic/i.test(name))return{group:"TONE",name};
  if(/^(in|out|mix)$|input|output|gain|level|trim|pan|width|balance|dry|wet|bypass|delta/i.test(name))return{group:"I/O",name};
  return{group:"GENERAL",name};
}
function parameterControl(param,selected){
  const normalizedStep=Math.max(0,+param.step||0);const toggle=param.toggle===true||/On\/Off|\bSolo$|^Bypass$|^Delta$|\bEnable(?:d)?$/i.test(param.name);const steps=normalizedStep>0?Math.round(1/normalizedStep):Infinity;const discrete=!toggle&&steps>=2&&steps<=32;const control=document.createElement("div");control.className=`parameter ${toggle?"toggle":discrete?"enum":""}`;control.dataset.index=param.index;control.dataset.value=param.value;const label=document.createElement("label");label.textContent=param.name||`Parameter ${param.index+1}`;control.append(label);
  const target=`${selected.trackId}|${selected.fxIndex}|${param.index}`;
  if(toggle){const button=document.createElement("button");button.dataset.role="toggle";button.dataset.value=param.value;button.textContent=param.formatted||(+param.value>.5?"ON":"OFF");button.classList.toggle("on",+param.value>.5);bindButton(button,()=>command("set_fx_param",target,+button.dataset.value>.5?0:1));control.append(button);return control}
  if(discrete){const select=document.createElement("select");select.setAttribute("aria-label",param.name);const choices=param.choices?.length?param.choices:Array.from({length:steps+1},(_,index)=>({value:Math.min(1,index*normalizedStep),label:`${Math.round(Math.min(1,index*normalizedStep)*100)}%`}));for(const choice of choices){const option=document.createElement("option");option.value=choice.value;option.textContent=choice.label;select.append(option)}const nearest=[...select.options].reduce((best,option)=>Math.abs(+option.value-param.value)<Math.abs(+best.value-param.value)?option:best,select.options[0]);if(nearest)select.value=nearest.value;select.onchange=()=>{control.dataset.value=select.value;pressFeedback(control);command("set_fx_param",target,select.value)};control.append(select);return control}
  control.classList.add("rotary");const knob=document.createElement("div");knob.className="knob";knob.setAttribute("role","slider");knob.setAttribute("aria-valuemin","0");knob.setAttribute("aria-valuemax","1");knob.setAttribute("aria-label",param.name);knob.innerHTML='<i></i><span></span>';paintKnob(knob,param.value);const output=document.createElement("output");output.textContent=param.formatted||`${Math.round(param.value*100)}%`;control.append(knob,output);let originY=0,originX=0,originValue=0,dragAxis=null;const update=event=>{const dx=event.clientX-originX;const dy=originY-event.clientY;if(!dragAxis&&Math.max(Math.abs(dx),Math.abs(dy))>=5)dragAxis=Math.abs(dy)>=Math.abs(dx)?"vertical":"horizontal";if(!dragAxis)return;const distance=dragAxis==="horizontal"?dx:dy;const value=rotaryDragValue(originValue,distance,event.pointerType);control.dataset.value=value;paintKnob(knob,value);output.textContent=`${Math.round(value*100)}%`;smoothCommand("set_fx_param",target,value)};knob.onpointerdown=event=>{event.preventDefault();knob.setPointerCapture(event.pointerId);originY=event.clientY;originX=event.clientX;originValue=+control.dataset.value||0;dragAxis=null;pointers.set(`fx:${param.index}`,event.pointerId);knob.classList.add("turning");control.classList.add("interacting")};knob.onpointermove=event=>{if(pointers.get(`fx:${param.index}`)===event.pointerId)update(event)};const end=event=>{if(pointers.get(`fx:${param.index}`)===event.pointerId){pointers.delete(`fx:${param.index}`);settleInteraction(`fx:${param.index}`);pressFeedback(control)}knob.classList.remove("turning");control.classList.remove("interacting")};knob.onpointerup=end;knob.onpointercancel=end;knob.onlostpointercapture=end;return control
}
function persistShow(){localStorage.setItem("rtr.snapshots",JSON.stringify(snapshots));localStorage.setItem("rtr.userKeys",JSON.stringify(userKeys));updateLiveKeys()}
function saveCurrentSnapshot(name){if(!state)return;const item={id:`snap-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`,name:name||`Snapshot ${snapshots.length+1}`,created:Date.now(),project:state.project.name,tracks:state.tracks.map(track=>({id:track.id,volume:track.volume,pan:track.pan,mute:track.mute,solo:track.solo})),fx:state.selectedFx?{trackId:state.selectedFx.trackId,fxIndex:state.selectedFx.fxIndex,id:state.selectedFx.id,parameters:state.selectedFx.parameters.map(param=>({index:param.index,value:param.value}))}:null};snapshots.unshift(item);snapshots=snapshots.slice(0,24);persistShow();renderSnapshotList();flashButton($("#quickSave"),"SAVED")}
function recallSnapshot(item){if(!item)return;for(const track of item.tracks){command("set_track_volume",track.id,track.volume);command("set_track_pan",track.id,track.pan);command("set_track_mute",track.id,track.mute?1:0);command("set_track_solo",track.id,track.solo?1:0)}if(item.fx){const liveFX=state?.tracks.find(track=>track.id===item.fx.trackId)?.fx.find(fx=>item.fx.id&&fx.id===item.fx.id);const fxIndex=liveFX?.index??item.fx.fxIndex;command("open_fx",`${item.fx.trackId}|${fxIndex}`);for(const param of item.fx.parameters)command("set_fx_param",`${item.fx.trackId}|${fxIndex}|${param.index}`,param.value)}flashButton($("#showPanel"),"RECALLING")}
function renderSnapshotList(){const list=$("#snapshotList");list.replaceChildren(...snapshots.map(item=>{const row=document.createElement("div");row.className="snapshot-row";row.innerHTML='<div><strong></strong><small></small></div><button class="recall">RECALL</button><div class="key-assign"></div><button class="danger">DELETE</button>';row.querySelector("strong").textContent=item.name;row.querySelector("small").textContent=`${item.project||"Project"} · ${new Date(item.created).toLocaleTimeString()}`;bindButton(row.querySelector(".recall"),()=>recallSnapshot(item));const keys=row.querySelector(".key-assign");for(let i=0;i<4;i++){const button=document.createElement("button");button.textContent=`KEY ${i+1}`;button.classList.toggle("assigned",userKeys[i]===item.id);bindButton(button,()=>{userKeys[i]=item.id;persistShow();renderSnapshotList()});keys.append(button)}bindButton(row.querySelector(".danger"),()=>{snapshots=snapshots.filter(snapshot=>snapshot.id!==item.id);userKeys=userKeys.map(id=>id===item.id?null:id);persistShow();renderSnapshotList()});return row}))}
function updateLiveKeys(){document.querySelectorAll("[data-user-key]").forEach(button=>{const item=snapshots.find(snapshot=>snapshot.id===userKeys[+button.dataset.userKey]);button.classList.toggle("assigned",Boolean(item));button.title=item?.name||"Unassigned"});const track=state?.tracks.find(item=>item.selected)||state?.tracks[0];document.querySelectorAll("[data-hot-fx]").forEach(button=>{const fx=track?.fx[+button.dataset.hotFx];button.classList.toggle("assigned",Boolean(fx));button.title=fx?.name||"Empty slot"})}
function flashButton(button,text){const original=button.textContent;button.textContent=text;button.classList.add("pending");setTimeout(()=>{button.textContent=original;button.classList.remove("pending")},900)}
function setConnection(status,text){els.connection.className=`connection ${status}`;els.connection.querySelector("span").textContent=text;if(els.pluginLatency){const quality=status==="online"?(latency>120?"slow":latency>50?"warn":"good"):status;els.pluginLatency.className=`plugin-latency ${quality}`;els.pluginLatency.querySelector("b").textContent=status==="online"?`${latency} ms`:status==="connecting"?"連線中":"離線"}}
$("#bankPrev").onclick=()=>{bank=Math.max(0,bank-1);render()};$("#bankNext").onclick=()=>{if(state){bank=Math.min(Math.ceil(state.tracks.length/bankSize)-1,bank+1);render()}};els.connection.onclick=()=>{els.host.value=settings.host;els.port.value=settings.port;$("#auto").checked=settings.auto;$("#details").textContent=`Current: ${settings.host}:${settings.port}`;els.settings.showModal()};$("#saveConnection").onclick=()=>{settings.host=els.host.value.trim();settings.port=els.port.value;settings.auto=$("#auto").checked;localStorage.setItem("rtr.connection",JSON.stringify(settings));connect()};bindButton($("#pluginBack"),closePlugin);bindButton(els.rackPrev,()=>adjacentRack(-1));bindButton(els.rackNext,()=>adjacentRack(1));bindButton($("#pluginBypass"),()=>activeFX&&command("set_fx_bypass",`${activeFX.trackId}|${activeFX.fxIndex}`,activeFX.enabled?1:0));$("#wake").onclick=async()=>{try{window.wakeLock=await navigator.wakeLock.request("screen");$("#wake").textContent="AWAKE"}catch{$("#wake").textContent="WAKE FAILED"}};
$("#showPanel").onclick=()=>{renderSnapshotList();$("#snapshots").showModal()};$("#closeSnapshots").onclick=()=>$("#snapshots").close();$("#quickSave").onclick=()=>saveCurrentSnapshot();$("#saveSnapshot").onclick=()=>{const input=$("#snapshotName");saveCurrentSnapshot(input.value.trim());input.value=""};document.querySelectorAll("[data-user-key]").forEach(button=>bindButton(button,()=>recallSnapshot(snapshots.find(item=>item.id===userKeys[+button.dataset.userKey]))));document.querySelectorAll("[data-hot-fx]").forEach(button=>bindButton(button,()=>{const track=state?.tracks.find(item=>item.selected)||state?.tracks[0];const fx=track?.fx[+button.dataset.hotFx];if(fx)openPlugin(track,fx)}));updateLiveKeys();
$("#closeFxBrowser").onclick=()=>els.fxBrowser.close();els.fxSearch.oninput=renderFxResults;$("#saveRackName").onclick=()=>{const name=$("#rackName").value.trim();if(renameTarget&&name)command("rename_track",renameTarget.id,name);renameTarget=null};
document.addEventListener("contextmenu",e=>{if(!e.target.closest("input"))e.preventDefault()});document.addEventListener("gesturestart",e=>e.preventDefault(),{passive:false});window.addEventListener("resize",()=>state&&render());if("serviceWorker" in navigator)navigator.serviceWorker.register("/service-worker.js");connect();
