import { eqPointerValue, rotaryDragValue } from "./control-physics.js";

const $ = (selector) => document.querySelector(selector);
const els = { mixer:$("#mixer"), project:$("#project"), connection:$("#connection"), bank:$("#bankLabel"), settings:$("#settings"), host:$("#host"), port:$("#port"), pluginView:$("#pluginView"), panel:$("#parameterPanel"), tabs:$("#parameterTabs"), rack:$("#rackChain"), surface:$("#pluginSurface"), visual:$("#pluginVisual"), fxBrowser:$("#fxBrowser"), fxSearch:$("#fxSearch"), fxResults:$("#fxResults") };
const settings = JSON.parse(localStorage.getItem("rtr.connection") || "null") || { host:location.hostname, port:location.port || "47830", auto:true };
// The origin that successfully served the app is the best authority after DHCP/network changes.
// Without this, a remembered WebSocket host can keep targeting yesterday's IP while the UI
// itself loads from today's IP, leaving a plausible-looking but disconnected mixer.
if (location.hostname && settings.host !== location.hostname) {
  settings.host = location.hostname;
  settings.port = location.port || "47830";
  localStorage.setItem("rtr.connection", JSON.stringify(settings));
}
let socket, heartbeat, reconnectTimer, state, bank=0, bankSize=8, latency=0, activeFX=null, activeParameterGroup=null, fxBrowserTrack=null, renameTarget=null, installedFX=null;
const pointers = new Map();
const interactionLocks = new Map();
const smoothCommands=new Map();let smoothFrame=0;
const EQ_GEOMETRY={width:1000,height:280,insetX:28,insetY:24};
let snapshots=JSON.parse(localStorage.getItem("rtr.snapshots")||"[]");
let userKeys=JSON.parse(localStorage.getItem("rtr.userKeys")||"[null,null,null,null]");

function connect() {
  clearTimeout(reconnectTimer); clearInterval(heartbeat);
  setConnection("connecting", "Connecting");
  socket?.close();
  socket = new WebSocket(`ws://${settings.host}:${settings.port}/ws`);
  socket.onopen = () => { setConnection("online", "REAPER"); socket.send(JSON.stringify({type:"hello",protocol:1})); heartbeat=setInterval(()=>socket.send(JSON.stringify({type:"heartbeat",at:Date.now()})),2000); };
  socket.onmessage = ({data}) => handle(JSON.parse(data));
  socket.onclose = () => { setConnection("offline", "Disconnected"); clearInterval(heartbeat); if(settings.auto) reconnectTimer=setTimeout(connect,1500); };
  socket.onerror = () => socket.close();
}
function handle(message) {
  if(message.type==="snapshot") { state=message.state; if(activeFX)renderPluginParameters();else render(); }
  if(message.type==="state_update" && state) { const changes=message.changes||{};for(const item of changes.meters||[]){const track=state.tracks.find(t=>t.id===item.id);if(track){track.meter=item.meter;track.signal=item.signal}}for(const item of changes.tracks||[]){const track=state.tracks.find(t=>t.id===item.id);if(!track)continue;for(const key of ["volume","pan","mute","solo","selected"])if(key in item)track[key]=item[key];for(const changedFX of item.fx||[]){const fx=track.fx.find(candidate=>changedFX.id?candidate.id===changedFX.id:candidate.index===changedFX.index);if(fx)fx.enabled=changedFX.enabled}}if(changes.selectedFx&&state.selectedFx&&changes.selectedFx.id===state.selectedFx.id){for(const changedParam of changes.selectedFx.parameters||[]){const param=state.selectedFx.parameters.find(candidate=>candidate.index===changedParam.index);if(param)Object.assign(param,changedParam)}}renderMeters();renderPluginSignal();if(changes.tracks?.length&&!activeFX)render();if(activeFX&&(changes.selectedFx?.parameters?.length||changes.tracks?.some(track=>track.fx?.length)))renderPluginParameters(); }
  if(message.type==="heartbeat") { latency=Math.max(0,Math.round((Date.now()-message.echo)/2));setConnection("online",`REAPER · ${latency} ms`); }
}
function command(action,target,value="") { if(socket?.readyState!==WebSocket.OPEN)return;const id=globalThis.crypto?.randomUUID?.()||`cmd-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;socket.send(JSON.stringify({type:"command",id,action,target,value})); }
function smoothCommand(action,target,value){smoothCommands.set(`${action}|${target}`,{action,target,value});if(smoothFrame)return;smoothFrame=requestAnimationFrame(()=>{smoothFrame=0;for(const item of smoothCommands.values())command(item.action,item.target,item.value);smoothCommands.clear()})}
function locallyControlled(key){const until=interactionLocks.get(key)||0;if(until>performance.now())return true;if(until)interactionLocks.delete(key);return pointers.has(key)}
function settleInteraction(key){interactionLocks.set(key,performance.now()+110);setTimeout(()=>{interactionLocks.delete(key);if(activeFX)renderPluginParameters()},120)}
function render(){
  els.project.textContent=state.project.name||"Untitled"; bankSize=innerWidth<1180?8:12; document.documentElement.style.setProperty("--bank-size",bankSize); const count=Math.max(1,Math.ceil(state.tracks.length/bankSize));bank=Math.min(bank,count-1);els.bank.textContent=`${bank+1} / ${count}`;
  els.mixer.replaceChildren(...state.tracks.slice(bank*bankSize,(bank+1)*bankSize).map(trackStrip)); renderMeters();updateLiveKeys();
}
function trackStrip(track){
  const strip=document.createElement("article");strip.className=`strip ${track.selected?"selected":""}`;strip.dataset.id=track.id;
  strip.innerHTML=`<div class="track-head"><button class="track-select"><b>RACK ${track.number}</b><span></span><i class="rack-meter"><em class="meter-fill"></em></i></button><button class="rename-track" aria-label="Rename rack">✎</button></div><div class="fx-list"></div><div class="buttons"><button class="mute">MUTE</button><button class="solo">SOLO</button></div>`;
  strip.querySelector(".track-head span").textContent=track.name||`Track ${track.number}`;strip.querySelector(".track-select").onpointerup=()=>command("select_track",track.id);strip.querySelector(".rename-track").onclick=()=>openRenameRack(track);
  bindButton(strip.querySelector(".mute"),()=>command("set_track_mute",track.id,track.mute?0:1),track.mute);bindButton(strip.querySelector(".solo"),()=>command("set_track_solo",track.id,track.solo?0:1),track.solo);
  const list=strip.querySelector(".fx-list");track.fx.forEach((fx,visibleIndex)=>{const row=document.createElement("div");row.className="fx";row.setAttribute("role","button");row.innerHTML=`<small>${visibleIndex+1}</small><span></span><button class="bypass ${fx.enabled?"":"off"}" aria-label="Toggle bypass">${fx.enabled?"IN":"OUT"}</button>`;row.querySelector("span").textContent=fx.name;row.onpointerdown=e=>{if(e.target.classList.contains("bypass"))return;e.preventDefault();row.setPointerCapture(e.pointerId);row.classList.add("pressed")};row.onpointerup=e=>{row.classList.remove("pressed");if(e.target.classList.contains("bypass"))return;openPlugin(track,fx)};row.onpointercancel=row.onlostpointercapture=()=>row.classList.remove("pressed");bindButton(row.querySelector(".bypass"),()=>command("set_fx_bypass",`${track.id}|${fx.index}`,fx.enabled?1:0));list.append(row)});for(let slot=track.fx.length;slot<Math.max(8,track.fx.length);slot++){const empty=document.createElement("button");empty.className="fx-empty";empty.innerHTML=`<small>${slot+1}</small><span>ADD PLUGIN</span>`;empty.onclick=()=>openFxBrowser(track);list.append(empty)}
  return strip;
}
async function openFxBrowser(track){
  fxBrowserTrack=track;$("#fxBrowserTrack").textContent=`${track.name||`Rack ${track.number}`} · add to the end of this chain`;els.fxSearch.value="";els.fxResults.replaceChildren();$("#fxBrowserStatus").textContent="Loading installed REAPER plug-ins…";els.fxBrowser.showModal();els.fxSearch.focus();
  if(!installedFX){try{const response=await fetch("/api/fx",{cache:"no-store"});if(!response.ok)throw new Error("inventory");installedFX=await response.json()}catch{$("#fxBrowserStatus").textContent="Restart the updated REAPER Bridge once to build the plug-in list.";return}}
  renderFxResults();
}
function renderFxResults(){
  if(!installedFX)return;const terms=els.fxSearch.value.trim().toLowerCase().split(/\s+/).filter(Boolean);const matches=installedFX.filter(fx=>terms.every(term=>`${fx.name} ${fx.ident}`.toLowerCase().includes(term))).slice(0,120);$("#fxBrowserStatus").textContent=`${matches.length}${matches.length===120?"+":""} shown · ${installedFX.length} installed`;
  els.fxResults.replaceChildren(...matches.map(fx=>{const button=document.createElement("button");button.className="fx-result";const type=(fx.name.match(/^([^:]+):/)?.[1]||"FX").toUpperCase();button.innerHTML='<b></b><span></span><small></small>';button.querySelector("b").textContent=type;button.querySelector("span").textContent=fx.name.replace(/^[^:]+:\s*/,"");button.querySelector("small").textContent=fx.ident||fx.name;button.onclick=()=>{if(!fxBrowserTrack)return;command("add_fx",fxBrowserTrack.id,fx.name);els.fxBrowser.close();flashButton($("#showPanel"),"ADDING FX")};return button}))
}
function openRenameRack(track){renameTarget=track;$("#rackName").value=track.name||`Track ${track.number}`;$("#renameRack").showModal();$("#rackName").focus();$("#rackName").select()}
function bindButton(button,callback,active=false){button.classList.toggle("active",active);button.onpointerdown=e=>{e.preventDefault();button.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{kind:"button",button});button.classList.add("pressed")};button.onpointerup=e=>{if(pointers.get(e.pointerId)?.button===button){button.classList.add("pending");callback()}pointers.delete(e.pointerId);button.classList.remove("pressed")};button.onpointercancel=button.onlostpointercapture=e=>{pointers.delete(e.pointerId);button.classList.remove("pressed")}}
function renderMeters(){if(!state)return;document.querySelectorAll(".strip").forEach(strip=>{const track=state.tracks.find(t=>t.id===strip.dataset.id);if(track){const peak=Math.max(...(track.meter||[-100]));strip.querySelector(".meter-fill").style.width=`${Math.max(0,Math.min(100,(peak+60)/60*100))}%`}})}
function openPlugin(track,fx){activeFX={trackId:track.id,fxIndex:fx.index,id:fx.id,name:fx.name,enabled:fx.enabled};activeParameterGroup=null;command("open_fx",`${track.id}|${fx.index}`);$("#pluginTrack").textContent=track.name;$("#pluginName").textContent=fx.name;renderRackChain(track);els.panel.dataset.key="";els.visual.dataset.key="";els.tabs.replaceChildren();els.panel.innerHTML='<div class="plugin-message">Loading real parameters from REAPER…</div>';els.visual.innerHTML='<div class="visual-loading">BUILDING TOUCH UI</div>';els.pluginView.hidden=false;renderPluginParameters()}
function closePlugin(){command("close_fx",activeFX?`${activeFX.trackId}|${activeFX.fxIndex}`:"");activeFX=null;activeParameterGroup=null;els.panel.dataset.key="";els.visual.dataset.key="";els.tabs.replaceChildren();els.pluginView.hidden=true;render()}
function adjacentPlugin(delta){if(!activeFX||!state)return;const track=state.tracks.find(item=>item.id===activeFX.trackId);if(!track)return;const position=track.fx.findIndex(fx=>activeFX.id?fx.id===activeFX.id:fx.index===activeFX.fxIndex);const next=track.fx[position+delta];if(next)openPlugin(track,next)}
function renderRackChain(track){els.rack.replaceChildren(...track.fx.map((fx,visibleIndex)=>{const button=document.createElement("button");const active=activeFX&&(activeFX.id?fx.id===activeFX.id:fx.index===activeFX.fxIndex);button.className=`rack-slot ${active?"active":""}`;button.innerHTML=`<small>SLOT ${visibleIndex+1}</small><span></span>`;button.querySelector("span").textContent=fx.name;bindButton(button,()=>openPlugin(track,fx));return button}))}
function renderPluginParameters(){
  const selected=state?.selectedFx;if(!activeFX||!selected||selected.trackId!==activeFX.trackId)return;if(selected.id&&activeFX.id===selected.id)activeFX.fxIndex=selected.fxIndex;else if(selected.fxIndex!==activeFX.fxIndex)return;activeFX.id=selected.id||activeFX.id;
  const params=usableParameters(selected.parameters,selected.name);
  const groups=new Map();for(const param of params){const descriptor=classifyParameter(param,selected.name);const renamed={...param,name:descriptor.name};if(!groups.has(descriptor.group))groups.set(descriptor.group,[]);groups.get(descriptor.group).push(renamed)}const groupNames=[...groups.keys()];if(!activeParameterGroup||!groups.has(activeParameterGroup))activeParameterGroup=/\bF6\b/i.test(selected.name)&&groups.has("BAND 1")?"BAND 1":groupNames.find(name=>name!=="I/O"&&name!=="GENERAL")||groupNames[0]||null;
  const key=`${selected.trackId}|${selected.fxIndex}|${activeParameterGroup}|${params.map(param=>`${param.index}:${param.name}:${param.toggle?1:0}:${param.step||0}`).join(";")}`;$("#pluginName").textContent=selected.name;
  const activeTrack=state.tracks.find(track=>track.id===activeFX.trackId);const liveFX=activeTrack?.fx.find(fx=>activeFX.id?fx.id===activeFX.id:fx.index===activeFX.fxIndex);if(liveFX){activeFX.fxIndex=liveFX.index;activeFX.enabled=liveFX.enabled;$("#pluginBypass").textContent=liveFX.enabled?"BYPASS":"BYPASSED";$("#pluginBypass").classList.toggle("active",!liveFX.enabled)}if(activeTrack){$("#pluginTrack").textContent=activeTrack.name;renderRackChain(activeTrack)}
  renderPluginVisual(selected,params);
  if(els.panel.dataset.key===key){for(const param of params){const shell=els.panel.querySelector(`.parameter[data-index="${param.index}"]`);if(!shell||locallyControlled(`fx:${param.index}`))continue;shell.dataset.value=param.value;const input=shell.querySelector("input[type=range]");const select=shell.querySelector("select");const knob=shell.querySelector(".knob");const output=shell.querySelector("output");const toggle=shell.querySelector("button[data-role=toggle]");if(input)input.value=param.value;if(select){const options=[...select.options];const nearest=options.reduce((best,option)=>Math.abs(+option.value-param.value)<Math.abs(+best.value-param.value)?option:best,options[0]);if(nearest)select.value=nearest.value}if(knob)paintKnob(knob,param.value);if(output)output.textContent=param.formatted||`${Math.round(param.value*100)}%`;if(toggle){toggle.dataset.value=param.value;toggle.textContent=param.formatted||(+param.value>.5?"ON":"OFF");toggle.classList.toggle("on",+param.value>.5);toggle.classList.remove("pending")}}return}
  if(!params.length){els.tabs.replaceChildren();els.panel.dataset.key=key;els.panel.innerHTML='<div class="plugin-message">This plug-in exposes no automatable parameters to REAPER.</div>';return}
  els.tabs.replaceChildren(...groupNames.map(name=>{const button=document.createElement("button");button.textContent=name;button.classList.toggle("active",name===activeParameterGroup);button.onclick=()=>{if(activeParameterGroup===name)return;activeParameterGroup=name;els.panel.dataset.key="";renderPluginParameters()};return button}));const section=document.createElement("section");section.className="parameter-section active-page";section.innerHTML='<h3></h3><div class="parameter-grid"></div>';section.querySelector("h3").textContent=activeParameterGroup;section.querySelector(".parameter-grid").replaceChildren(...(groups.get(activeParameterGroup)||[]).map(param=>parameterControl(param,selected)));els.panel.dataset.key=key;els.panel.replaceChildren(section)
}
function usableParameters(parameters=[]){
  const midiStart=parameters.findIndex(param=>/^Pitch Bend$/i.test(param.name));
  const hasHostMidiBlock=midiStart>=0&&parameters.slice(midiStart+1,midiStart+8).some(param=>/^(After Touch|Bank Select|Modulation Wheel|Breath Controller|Foot Controller|Control \d+)$/i.test(param.name));
  const core=hasHostMidiBlock?parameters.slice(0,midiStart):parameters;
  const utilities=parameters.filter(param=>/^(Bypass|Wet|Delta)$/i.test(param.name));
  return [...core,...utilities.filter(param=>!core.some(item=>item.index===param.index))].filter(param=>param.name&&!/^Control \d+$/i.test(param.name));
}
function renderPluginVisual(selected,params){
  const isF6=/\bF6\b/i.test(selected.name)&&[1,2,3,4,5,6].every(band=>params.some(param=>param.name===`Band ${band} Freq`)&&params.some(param=>param.name===`Band ${band} Gain`));
  els.pluginView.style.setProperty("--plugin-accent",isF6?"#d99058":/delay|echo/i.test(selected.name)?"#d6ad39":"#28a7cf");
  const visualKey=`${selected.trackId}|${selected.fxIndex}|${isF6?"f6":"generic"}`;
  if(els.visual.dataset.key!==visualKey){els.visual.dataset.key=visualKey;isF6?buildF6Visual(selected,params):buildGenericVisual(selected,params)}
  if(isF6)updateF6Visual(params);renderPluginSignal();
}
function buildF6Visual(selected,params){
  els.visual.innerHTML='<div class="visual-head"><div><strong>F6 TOUCH EQ</strong><span>Precision band control · live REAPER feedback</span></div><div class="live-levels"><span>IN<i><b data-level="input"></b></i></span><span>OUT<i><b data-level="output"></b></i></span></div></div><svg class="eq-graph" viewBox="0 0 1000 280" preserveAspectRatio="none" aria-label="Six band EQ graph"><g class="eq-grid"></g><path class="rt-spectrum"></path><path class="eq-curve"></path><g class="eq-bands"></g></svg>';
  const grid=els.visual.querySelector(".eq-grid");for(let x=0;x<=1000;x+=100){const line=document.createElementNS("http://www.w3.org/2000/svg","line");line.setAttribute("x1",x);line.setAttribute("x2",x);line.setAttribute("y1",0);line.setAttribute("y2",EQ_GEOMETRY.height);grid.append(line)}for(let y=35;y<EQ_GEOMETRY.height;y+=35){const line=document.createElementNS("http://www.w3.org/2000/svg","line");line.setAttribute("x1",0);line.setAttribute("x2",EQ_GEOMETRY.width);line.setAttribute("y1",y);line.setAttribute("y2",y);grid.append(line)}
  const bands=els.visual.querySelector(".eq-bands");for(let band=1;band<=6;band++){const group=document.createElementNS("http://www.w3.org/2000/svg","g");group.dataset.band=band;const halo=document.createElementNS("http://www.w3.org/2000/svg","circle");halo.setAttribute("r",25);halo.setAttribute("class","band-halo");const node=document.createElementNS("http://www.w3.org/2000/svg","circle");node.setAttribute("r",14);node.setAttribute("class","band-node");const label=document.createElementNS("http://www.w3.org/2000/svg","text");label.setAttribute("y",5);label.setAttribute("text-anchor","middle");label.textContent=band;group.append(halo,node,label);bands.append(group)}
  const graph=els.visual.querySelector(".eq-graph");const move=(event,band)=>{const point=eqPointerValue(event.clientX,event.clientY,graph.getBoundingClientRect(),EQ_GEOMETRY);const freq=params.find(param=>param.name===`Band ${band} Freq`);const gain=params.find(param=>param.name===`Band ${band} Gain`);if(!freq||!gain)return;graph.querySelector(`[data-band="${band}"]`).setAttribute("transform",`translate(${point.x} ${point.y})`);smoothCommand("set_fx_param",`${selected.trackId}|${selected.fxIndex}|${freq.index}`,point.frequency);smoothCommand("set_fx_param",`${selected.trackId}|${selected.fxIndex}|${gain.index}`,point.gain)};graph.onpointerdown=event=>{const group=event.target.closest("[data-band]");if(!group)return;event.preventDefault();const band=+group.dataset.band;if(activeParameterGroup!==`BAND ${band}`){activeParameterGroup=`BAND ${band}`;els.panel.dataset.key="";renderPluginParameters()}graph.setPointerCapture(event.pointerId);pointers.set(`graph:${band}`,event.pointerId);move(event,band)};graph.onpointermove=event=>{for(let band=1;band<=6;band++)if(pointers.get(`graph:${band}`)===event.pointerId)move(event,band)};const end=event=>{for(let band=1;band<=6;band++)if(pointers.get(`graph:${band}`)===event.pointerId){pointers.delete(`graph:${band}`);settleInteraction(`graph:${band}`)}};graph.onpointerup=end;graph.onpointercancel=end;graph.onlostpointercapture=end;
}
function updateF6Visual(params){const points=[];for(let band=1;band<=6;band++){if(locallyControlled(`graph:${band}`))continue;const freq=params.find(param=>param.name===`Band ${band} Freq`);const gain=params.find(param=>param.name===`Band ${band} Gain`);const enabled=params.find(param=>param.name===`Band ${band} On/Off`);if(!freq||!gain)continue;const x=EQ_GEOMETRY.insetX+(+freq.value*(EQ_GEOMETRY.width-EQ_GEOMETRY.insetX*2));const y=EQ_GEOMETRY.insetY+((1-(+gain.value))*(EQ_GEOMETRY.height-EQ_GEOMETRY.insetY*2));const group=els.visual.querySelector(`[data-band="${band}"]`);group?.setAttribute("transform",`translate(${x} ${y})`);group?.classList.toggle("off",enabled&&+enabled.value<.5);points.push([x,y])}const middle=EQ_GEOMETRY.height/2;const path=els.visual.querySelector(".eq-curve");if(path&&points.length)path.setAttribute("d",`M 0 ${middle} ${points.sort((a,b)=>a[0]-b[0]).map(point=>`L ${point[0]} ${point[1]}`).join(" ")} L ${EQ_GEOMETRY.width} ${middle}`)}
function buildGenericVisual(selected,params){const groups=[...new Set(params.map(param=>classifyParameter(param,selected.name).group))].slice(0,6);els.visual.innerHTML='<div class="generic-visual"><div class="fx-glyph">FX</div><div class="generic-title"><strong></strong><span></span><div class="visual-tags"></div><div class="live-levels"><span>IN<i><b data-level="input"></b></i></span><span>OUT<i><b data-level="output"></b></i></span></div></div><svg viewBox="0 0 500 100" preserveAspectRatio="none"><path class="rt-spectrum-line" d="M0 80 L500 80"></path></svg></div>';els.visual.querySelector(".generic-title strong").textContent=selected.name;els.visual.querySelector(".generic-title span").textContent=`${params.length} live controls from REAPER`;const tags=els.visual.querySelector(".visual-tags");for(const group of groups){const tag=document.createElement("b");tag.textContent=group;tags.append(tag)}}
function renderPluginSignal(){if(!activeFX||!state||!els.visual)return;const track=state.tracks.find(item=>item.id===activeFX.trackId);if(!track)return;const signal=track.signal;const input=Math.max(+(signal?.left||0),+(signal?.right||0));const outputDb=Math.max(...(track.meter||[-100]));const output=Math.max(0,Math.min(1,(outputDb+60)/60));const inputBar=els.visual.querySelector('[data-level="input"]');const outputBar=els.visual.querySelector('[data-level="output"]');if(inputBar)inputBar.style.width=`${Math.max(0,Math.min(100,input*100))}%`;if(outputBar)outputBar.style.width=`${output*100}%`;const spectrum=signal?.spectrum;if(!Array.isArray(spectrum)||!spectrum.length)return;const eqPath=els.visual.querySelector(".rt-spectrum");if(eqPath){const points=spectrum.map((value,index)=>`${index/(spectrum.length-1)*EQ_GEOMETRY.width} ${(1-Math.max(0,Math.min(1,+value||0)))*(EQ_GEOMETRY.height-10)+5}`);eqPath.setAttribute("d",`M 0 ${EQ_GEOMETRY.height} L ${points.join(" L ")} L ${EQ_GEOMETRY.width} ${EQ_GEOMETRY.height} Z`)}const genericPath=els.visual.querySelector(".rt-spectrum-line");if(genericPath){const points=spectrum.map((value,index)=>`${index/(spectrum.length-1)*500} ${(1-Math.max(0,Math.min(1,+value||0)))*90+5}`);genericPath.setAttribute("d",`M ${points.join(" L ")}`)}}
function paintKnob(knob,value){const normalized=Math.max(0,Math.min(1,+value||0));knob.style.setProperty("--angle",`${-135+normalized*270}deg`);knob.style.setProperty("--fill",`${normalized*75}%`);knob.setAttribute("aria-valuenow",normalized)}
function classifyParameter(param,fxName=""){
  const name=(param.name||`Parameter ${param.index+1}`).trim();
  const indexed=name.match(/^(Band|Channel|Osc(?:illator)?|LFO|Envelope|Env|Filter|Layer|Part)\s*(\d+)\s*[-:]?\s*(.+)$/i);
  if(indexed)return{group:`${indexed[1].toUpperCase()} ${indexed[2]}`,name:indexed[3]};
  if(/\bF6\b/i.test(fxName)&&/^(HPF|LPF)/i.test(name))return{group:"GLOBAL / FILTERS",name};
  if(/threshold|ratio|attack|release|knee|range|compress|limiter|gate|expan|transient|hold/i.test(name))return{group:"DYNAMICS",name};
  if(/frequency|\bfreq\b|\bq\b|filter|cutoff|resonan|high.?pass|low.?pass|\bHPF\b|\bLPF\b|\bEQ\b|shelf|bell/i.test(name))return{group:"FILTER / EQ",name};
  if(/\bLFO\b|modulat|chorus|flang|phaser|depth|waveform|shape/i.test(name))return{group:"MODULATION",name};
  if(/delay|\btime\b|tempo|sync|\brate\b|speed|feedback|pre.?delay|division/i.test(name))return{group:"TIME",name};
  if(/drive|satur|distort|tone|color|colour|warm|character|harmonic/i.test(name))return{group:"TONE",name};
  if(/^(in|out|mix)$|input|output|gain|level|trim|pan|width|balance|dry|wet|bypass|delta/i.test(name))return{group:"I/O",name};
  return{group:"GENERAL",name};
}
function parameterControl(param,selected){
  const normalizedStep=Math.max(0,+param.step||0);const toggle=param.toggle===true||/On\/Off|\bSolo$|^Bypass$|^Delta$|\bEnable(?:d)?$/i.test(param.name);const steps=normalizedStep>0?Math.round(1/normalizedStep):Infinity;const discrete=!toggle&&steps>=2&&steps<=32;const control=document.createElement("div");control.className=`parameter ${toggle?"toggle":discrete?"enum":""}`;control.dataset.index=param.index;control.dataset.value=param.value;const label=document.createElement("label");label.textContent=param.name||`Parameter ${param.index+1}`;control.append(label);
  const target=`${selected.trackId}|${selected.fxIndex}|${param.index}`;
  if(toggle){const button=document.createElement("button");button.dataset.role="toggle";button.dataset.value=param.value;button.textContent=param.formatted||(+param.value>.5?"ON":"OFF");button.classList.toggle("on",+param.value>.5);bindButton(button,()=>command("set_fx_param",target,+button.dataset.value>.5?0:1));control.append(button);return control}
  if(discrete){const select=document.createElement("select");select.setAttribute("aria-label",param.name);const choices=param.choices?.length?param.choices:Array.from({length:steps+1},(_,index)=>({value:Math.min(1,index*normalizedStep),label:`${Math.round(Math.min(1,index*normalizedStep)*100)}%`}));for(const choice of choices){const option=document.createElement("option");option.value=choice.value;option.textContent=choice.label;select.append(option)}const nearest=[...select.options].reduce((best,option)=>Math.abs(+option.value-param.value)<Math.abs(+best.value-param.value)?option:best,select.options[0]);if(nearest)select.value=nearest.value;select.onchange=()=>{control.dataset.value=select.value;command("set_fx_param",target,select.value)};control.append(select);return control}
  control.classList.add("rotary");const knob=document.createElement("div");knob.className="knob";knob.setAttribute("role","slider");knob.setAttribute("aria-valuemin","0");knob.setAttribute("aria-valuemax","1");knob.setAttribute("aria-label",param.name);knob.innerHTML='<i></i><span></span>';paintKnob(knob,param.value);const output=document.createElement("output");output.textContent=param.formatted||`${Math.round(param.value*100)}%`;control.append(knob,output);let originY=0,originX=0,originValue=0,dragAxis=null;const update=event=>{const dx=event.clientX-originX;const dy=originY-event.clientY;if(!dragAxis&&Math.max(Math.abs(dx),Math.abs(dy))>=5)dragAxis=Math.abs(dy)>=Math.abs(dx)?"vertical":"horizontal";if(!dragAxis)return;const distance=dragAxis==="horizontal"?dx:dy;const value=rotaryDragValue(originValue,distance,event.pointerType);control.dataset.value=value;paintKnob(knob,value);output.textContent=`${Math.round(value*100)}%`;smoothCommand("set_fx_param",target,value)};knob.onpointerdown=event=>{event.preventDefault();knob.setPointerCapture(event.pointerId);originY=event.clientY;originX=event.clientX;originValue=+control.dataset.value||0;dragAxis=null;pointers.set(`fx:${param.index}`,event.pointerId);knob.classList.add("turning")};knob.onpointermove=event=>{if(pointers.get(`fx:${param.index}`)===event.pointerId)update(event)};const end=event=>{if(pointers.get(`fx:${param.index}`)===event.pointerId){pointers.delete(`fx:${param.index}`);settleInteraction(`fx:${param.index}`)}knob.classList.remove("turning")};knob.onpointerup=end;knob.onpointercancel=end;knob.onlostpointercapture=end;return control
}
function persistShow(){localStorage.setItem("rtr.snapshots",JSON.stringify(snapshots));localStorage.setItem("rtr.userKeys",JSON.stringify(userKeys));updateLiveKeys()}
function saveCurrentSnapshot(name){if(!state)return;const item={id:`snap-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`,name:name||`Snapshot ${snapshots.length+1}`,created:Date.now(),project:state.project.name,tracks:state.tracks.map(track=>({id:track.id,volume:track.volume,pan:track.pan,mute:track.mute,solo:track.solo})),fx:state.selectedFx?{trackId:state.selectedFx.trackId,fxIndex:state.selectedFx.fxIndex,id:state.selectedFx.id,parameters:state.selectedFx.parameters.map(param=>({index:param.index,value:param.value}))}:null};snapshots.unshift(item);snapshots=snapshots.slice(0,24);persistShow();renderSnapshotList();flashButton($("#quickSave"),"SAVED")}
function recallSnapshot(item){if(!item)return;for(const track of item.tracks){command("set_track_volume",track.id,track.volume);command("set_track_pan",track.id,track.pan);command("set_track_mute",track.id,track.mute?1:0);command("set_track_solo",track.id,track.solo?1:0)}if(item.fx){const liveFX=state?.tracks.find(track=>track.id===item.fx.trackId)?.fx.find(fx=>item.fx.id&&fx.id===item.fx.id);const fxIndex=liveFX?.index??item.fx.fxIndex;command("open_fx",`${item.fx.trackId}|${fxIndex}`);for(const param of item.fx.parameters)command("set_fx_param",`${item.fx.trackId}|${fxIndex}|${param.index}`,param.value)}flashButton($("#showPanel"),"RECALLING")}
function renderSnapshotList(){const list=$("#snapshotList");list.replaceChildren(...snapshots.map(item=>{const row=document.createElement("div");row.className="snapshot-row";row.innerHTML='<div><strong></strong><small></small></div><button class="recall">RECALL</button><div class="key-assign"></div><button class="danger">DELETE</button>';row.querySelector("strong").textContent=item.name;row.querySelector("small").textContent=`${item.project||"Project"} · ${new Date(item.created).toLocaleTimeString()}`;bindButton(row.querySelector(".recall"),()=>recallSnapshot(item));const keys=row.querySelector(".key-assign");for(let i=0;i<4;i++){const button=document.createElement("button");button.textContent=`KEY ${i+1}`;button.classList.toggle("assigned",userKeys[i]===item.id);bindButton(button,()=>{userKeys[i]=item.id;persistShow();renderSnapshotList()});keys.append(button)}bindButton(row.querySelector(".danger"),()=>{snapshots=snapshots.filter(snapshot=>snapshot.id!==item.id);userKeys=userKeys.map(id=>id===item.id?null:id);persistShow();renderSnapshotList()});return row}))}
function updateLiveKeys(){document.querySelectorAll("[data-user-key]").forEach(button=>{const item=snapshots.find(snapshot=>snapshot.id===userKeys[+button.dataset.userKey]);button.classList.toggle("assigned",Boolean(item));button.title=item?.name||"Unassigned"});const track=state?.tracks.find(item=>item.selected)||state?.tracks[0];document.querySelectorAll("[data-hot-fx]").forEach(button=>{const fx=track?.fx[+button.dataset.hotFx];button.classList.toggle("assigned",Boolean(fx));button.title=fx?.name||"Empty slot"})}
function flashButton(button,text){const original=button.textContent;button.textContent=text;button.classList.add("pending");setTimeout(()=>{button.textContent=original;button.classList.remove("pending")},900)}
function setConnection(status,text){els.connection.className=`connection ${status}`;els.connection.querySelector("span").textContent=text}
$("#bankPrev").onclick=()=>{bank=Math.max(0,bank-1);render()};$("#bankNext").onclick=()=>{if(state){bank=Math.min(Math.ceil(state.tracks.length/bankSize)-1,bank+1);render()}};els.connection.onclick=()=>{els.host.value=settings.host;els.port.value=settings.port;$("#auto").checked=settings.auto;$("#details").textContent=`Current: ${settings.host}:${settings.port}`;els.settings.showModal()};$("#saveConnection").onclick=()=>{settings.host=els.host.value.trim();settings.port=els.port.value;settings.auto=$("#auto").checked;localStorage.setItem("rtr.connection",JSON.stringify(settings));connect()};$("#pluginBack").onclick=closePlugin;$("#pluginPrev").onclick=()=>adjacentPlugin(-1);$("#pluginNext").onclick=()=>adjacentPlugin(1);$("#pluginBypass").onclick=()=>activeFX&&command("set_fx_bypass",`${activeFX.trackId}|${activeFX.fxIndex}`,activeFX.enabled?1:0);$("#wake").onclick=async()=>{try{window.wakeLock=await navigator.wakeLock.request("screen");$("#wake").textContent="AWAKE"}catch{$("#wake").textContent="WAKE FAILED"}};
$("#showPanel").onclick=()=>{renderSnapshotList();$("#snapshots").showModal()};$("#closeSnapshots").onclick=()=>$("#snapshots").close();$("#quickSave").onclick=()=>saveCurrentSnapshot();$("#saveSnapshot").onclick=()=>{const input=$("#snapshotName");saveCurrentSnapshot(input.value.trim());input.value=""};document.querySelectorAll("[data-user-key]").forEach(button=>bindButton(button,()=>recallSnapshot(snapshots.find(item=>item.id===userKeys[+button.dataset.userKey]))));document.querySelectorAll("[data-hot-fx]").forEach(button=>bindButton(button,()=>{const track=state?.tracks.find(item=>item.selected)||state?.tracks[0];const fx=track?.fx[+button.dataset.hotFx];if(fx)openPlugin(track,fx)}));updateLiveKeys();
$("#closeFxBrowser").onclick=()=>els.fxBrowser.close();els.fxSearch.oninput=renderFxResults;$("#saveRackName").onclick=()=>{const name=$("#rackName").value.trim();if(renameTarget&&name)command("rename_track",renameTarget.id,name);renameTarget=null};
document.addEventListener("contextmenu",e=>{if(!e.target.closest("input"))e.preventDefault()});document.addEventListener("gesturestart",e=>e.preventDefault(),{passive:false});window.addEventListener("resize",()=>state&&render());if("serviceWorker" in navigator)navigator.serviceWorker.register("/service-worker.js");connect();
